import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

interface MyMetadata {
  title: string;
  description: string;
}

export const metadata: MyMetadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title || ""}</title>
        <meta name="description" content={metadata.description || ""} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
